buildings:
distribution:
  battery_size: 30 #this is in GW; Biggest value the battery can carry
  battery_value: 10 #this is in GW; Starting value in the battery
electricity:
public_infrastructure:
testing:
transport:
world:
  environment:
    delay: 1 #seconds it takes for one hour to pass in the simulation
  clock:
    date: '1.1.2100, 00:00:00' #stick to this exact format
  weather:
    weather: 'rain' #sunny, cloudy, rain, snow
    season: 'winter'  #summer, autumn, winter, spring