buildings:
distribution:
  battery_size: 30 #this is in GW; Biggest value the battery can carry
  battery_value: 10 #this is in GW; Starting value in the battery
electricity:
public_infrastructure:
testing:
transport:
world:
  time: 1900
  weather: